version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  system_info:
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
  setup:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  build:
    executor:
      name: default
    steps:
      - system_info
      - checkout
      - setup
      - run:
          name: Build
          command: yarn build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/workspace
      - add_ssh_keys:
          fingerprints:
            - "da:6c:1b:af:9a:bd:c7:0f:b8:b0:aa:28:ca:d7:50:fc"
      - run:
          name: Deploy
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy

workflows:
  build-deploy-flow:
    jobs:
      - build:
          context: spajam-2019-qualification
          filters:
            branches:
              ignore:
                - master
      - deploy:
          context: spajam-2019-qualification
          requires:
            - build
          filters:
            branches:
              only:
                - source
